const CUSTOM_EVENT_NAME = "__CHROME_EMITTER_A__";
const SPECIAL_CUSTOM_EVENT_NAME = "__CHROME_EMITTER_B__";
const SYNC_EVENT_NAME = "__CHROME_SYNC_NAME__";
const SYNC_SUFFIX = "@__CHROME_SUFFIX__";
const TIME_KEY = "__time__";
const DATA_KEY = "__data__";
const HAS_LISTEN = "__CHROME_HAS_LISTEN__";

module.exports.CUSTOM_EVENT_NAME = CUSTOM_EVENT_NAME;
module.exports.SPECIAL_CUSTOM_EVENT_NAME = SPECIAL_CUSTOM_EVENT_NAME;
module.exports.SYNC_EVENT_NAME = SYNC_EVENT_NAME;
module.exports.SYNC_SUFFIX = SYNC_SUFFIX;
module.exports.TIME_KEY = TIME_KEY;
module.exports.DATA_KEY = DATA_KEY;
module.exports.HAS_LISTEN = HAS_LISTEN;
